services:
  frontend:
    build: ./frontend  # Path to your frontend Dockerfile
    ports:
      - "3000:3000"  # Expose the frontend on port 3000
    environment:
      NEXT_PUBLIC_API_URL: http://web:8000  # API URL pointing to the backend
    depends_on:
      - web  # Ensure backend starts before frontend

  web:
    build: ./backend/djangobnb_backend  # Path to your backend (Django) Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangobnb_backend/:/usr/src/djangobnb_backend/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=djangobnb

volumes:
  postgres_data: